from snakemake.utils import min_version

min_version("7.18.2")

if 'use_conda' in config and config['use_conda'] and not workflow.use_conda:
    print("Using conda by default. Modify the use_conda "
            "setting in the config to change this behavior")
    workflow.use_conda = True

configfile: "config/config.yaml"

include: "rules/compile-problems.smk"


rule all:
    input:
        lambda wildcards: checkpoints.compile_all_problems.get(**wildcards).output[0]