version: "3.9"
services:
  data-generator:
    build:
      context: .
      target: data_generator
      args:
        - ROOTDIR=/done_soon
        - MODE=features
        - PROBLEM_SOURCE=all
    depends_on:
      - seed
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=test
    volumes:
      - mongodb_data_container:/data/db
    ports:
      - "27017:27017"
  seed:
    build:
      context: .
      target: seed_db
      args:
        - ROOTDIR=/done_soon
        - PROBLEM_SOURCE=all
    depends_on:
      - mongodb

volumes:
  mongodb_data_container:
